apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: vrushalikudande/my-fastapi-app
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config  
              key: database_url  # Using incorrect value from ConfigMap

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: my-app
  type: NodePort
