apiVersion: v1
kind: ConfigMap
metadata:
  name: anomaly-detector-config
  namespace: logging
data:
  DETECTION_INTERVAL: "60"  # Detection interval in seconds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detector
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detector
  template:
    metadata:
      labels:
        app: anomaly-detector
    spec:
      containers:
        - name: anomaly-detector
          image: vrushalikudande/anomaly-detector
          command: ["python"]
          args: ["anomaly_detector.py", "--interval", "$(DETECTION_INTERVAL)"]
          env:
            - name: DETECTION_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: anomaly-detector-config
                  key: DETECTION_INTERVAL
          volumeMounts:
            - name: fb-shared
              mountPath: /fluent-bit/etc/shared
      volumes:
        - name: fb-shared
          hostPath:
            path: /var/lib/fluent-bit/shared
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector
  namespace: logging
spec:
  selector:
    app: anomaly-detector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
